objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <inlineHelpText>How does the contact identify their gender?</inlineHelpText>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/customerDetails_Endpoint__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Details of the ourFriends service endpoint for specific customer details</description>
    <fields>
        <fullName>endpoint_url__c</fullName>
        <label>endpoint_url</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Customer Details Endpoint</label>
</CustomObject>

globalValueSets/Gender.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Non-binary</fullName>
    </customValue>
    <customValue>
        <fullName>Prefer not to disclose</fullName>
    </customValue>
    <customValue>
        <fullName>Transgender</fullName>
    </customValue>
    <description>How does the contact identify their gender?</description>
    <masterLabel>Gender</masterLabel>
</GlobalValueSet>

classes/ourFriends_createNewContactsBatchTest.cls
@isTest
private class ourFriends_createNewContactsBatchTest {

    private static Contact testcon;
    private static customerDetails_Endpoint__c EP;
    
    static void prepareTestData(){
    	
    	//  Insert Custom Setting record for endpoint
    	EP = new customerDetails_Endpoint__c(
    		Name = 'All Customers',
    		endpoint_url__c = 'https://sheltered-depths-66346.herokuapp.com/customers'
    	);
    	insert EP;
    	
    	//  Insert Account
    	Account A = new Account(
    		Name = 'OVO Assignment'
    	);
    	insert A;
    	
    	//  Insert test Contact record
    	testCon = new Contact(
    		FirstName = 'Morty',
    		LastName = 'Smith',
    		Gender__c = 'Male',
    		Salutation = 'Mr'
    	);
    	insert testCon;
    }
	
    static testMethod void testNewFriendsBatch() {
        prepareTestData();
        //  Set mock callout class
    	Test.setMock(HttpCalloutMock.class, new Mock_NewFriends());
    	
    	//  Invoke batch
    	ourFriends_createNewContactsBatch ncb= new ourFriends_createNewContactsBatch();
		database.executebatch(ncb);
        
    }
}